name: soft_studio_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-282.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  syncfusion_flutter_calendar: ^25.1.39
  timezone: ^0.9.2
  google_fonts: ^6.2.1
  provider: ^6.0.1
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0+1
  kalender: ^0.4.1
  flashy_tab_bar2: ^0.0.10
  line_awesome_flutter: ^3.0.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: openSans
      fonts:
        - asset: lib/assets/OpenSans-VariableFont.ttf

assets:
  - google_fonts/
